version: '2'
services:

  wordpress:
    image: wordpress:4.9.5-php5.6-apache
    ports:
      - 8080:80
    environment:
      WORD_PRESS_DB_PASSWORD: pw

  mongo:
    image: mongo
    environment:
      MONGODB_PASSWORD: pw
    ports:
      - 8081:27017
